//Categorias//
export const TODAS_CATEGORIAS = 'TODAS_CATEGORIAS'

//Posts//
export const TODOS_POSTS = 'TODOS_POSTS';
export const ADICIONAR_POST = 'ADICIONAR_POST'
export const EDITAR_POST = 'EDITAR_POST';
export const APAGAR_POST = 'APAGAR_POST';
export const PEGAR_POST = 'PEGAR_POST';
export const VOTAR_POST = 'VOTAR_POST';
export const ORDENA_POSTS = 'ORDENA_POSTS';

//Comentários//
export const TODOS_COMENTARIOS = 'TODOS_COMENTARIOS';
export const ADICIONAR_COMENTARIO = 'ADICIONAR_COMENTARIO';
export const DELETAR_COMENTARIO = 'DELETAR_COMENTARIO';
export const VOTAR_COMENTARIO = 'VOTAR_COMENTARIO'
export const EDITAR_COMENTARIO = 'EDITAR_COMENTARIO';
export const MUDAVIEW_COMENTARIO = 'MUDAVIEW_COMENTARIO';